export const imageManifest: Record<string, string> = {
  "b1": "/images/menu/b1.png",
  "b2": "/images/menu/b2.png",
  "b3": "/images/menu/b3.png",
  "b4": "/images/menu/b4.png",
  "b5": "/images/menu/b5.png",
  "b6": "/images/menu/b6.png",
  "b7": "/images/menu/b7.png",
  "b8": "/images/menu/b8.png",
  "b9": "/images/menu/b9.png",
  "b10": "/images/menu/b10.png",
  "d4": "/images/menu/d4.png",
  "d8": "/images/menu/d8.png",
  "d9": "/images/menu/d9.png",
  "ja4": "/images/menu/ja4.png",
  "k4": "/images/menu/k4.png",
  "ki9": "/images/menu/ki9.png",
  "pa14": "/images/menu/pa14.png",
  "sr2": "/images/menu/sr2.png",
  "v6": "/images/menu/v6.png",
  "w5": "/images/menu/w5.png",
  "w6": "/images/menu/w6.png",
  "w7": "/images/menu/w7.png",
  "w8": "/images/menu/w8.png",
  "z1": "/images/menu/z1.png",
  "z5": "/images/menu/z5.png",
  "z6": "/images/menu/z6.png",
};
